DROP TABLE IF EXISTS Movie;
DROP TABLE IF EXISTS MovieGenre;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Starred;
DROP TABLE IF EXISTS Actor;

CREATE TABLE Movie (
    movieID VARCHAR(15) NOT NULL PRIMARY KEY,
    movieTitle TEXT NOT NULL,
    yearReleased INT NOT NULL,
    runtimeMinutes INT NOT NULL,
    movieRating FLOAT NOT NULL
);

CREATE TABLE Genre (
    genreName VARCHAR(50) NOT NULL,
    genreID VARCHAR(3) NOT NULL PRIMARY KEY
);

CREATE TABLE MovieGenre (
    movieID VARCHAR(15) NOT NULL REFERENCES Movie(movieID),
    genreID VARCHAR(3) NOT NULL REFERENCES Genre(genreID),
    PRIMARY KEY(movieID, genreID)
);

CREATE TABLE Actor (
    actorID VARCHAR(15) NOT NULL PRIMARY KEY,
    actorName VARCHAR(60) NOT NULL
);

CREATE TABLE Starred (
    movieID VARCHAR(15) NOT NULL REFERENCES Movie(movieID),
    actorID VARCHAR(15) NOT NULL REFERENCES Actor(actorID),
    PRIMARY KEY(movieID, actorID)
);